### ISSUE TITLE
Incorrect mime type

### ISSUE THREAD

**Issue by mitajunior** [mitsuoka/mime_type#18]
Trying to record/pick videos using flutte but when I do 
```
lookupMimeType(file.path, headerBytes: [0xFF, 0xD8]).split('/');
```
it return image, jpeg but its an mp4 video, what could be the issue or what am I doing wrong?

**Comment by Molkars** [comment]
The lookupMimeType function is part of the [mime](https://github.com/dart-lang/mime) library, NOT this library.

In any case, I would suggest debugging the value of file.path, your issue is most likely caused by the file variable pointing to a JPG/JPEG image file rather than an MP4 video file.

As you can see (here)[https://github.com/dart-lang/mime/blob/master/lib/src/default_extension_map.dart#L467] the mime type of a .mp4 file is `video/mp4` and the mime type for a .jpeg or .jpg, ((here)[https://github.com/dart-lang/mime/blob/master/lib/src/default_extension_map.dart#L362]) file is `image/jpeg`.

**Comment by Molkars** [comment]
The code in question does not belong to this library, pursue any additional assistance in [dartlang's mime library](https://github.com/dart-lang/mime)
